-- MySQL Script generated by MySQL Workbench
-- Fri Jun  7 10:27:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sys_ecommerce_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sys_ecommerce_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sys_ecommerce_db` DEFAULT CHARACTER SET utf8 ;
USE `sys_ecommerce_db` ;

-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`estoque` (
  `idestoque` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `data_criacao` DATE NOT NULL,
  `data_modificado` DATE NOT NULL,
  PRIMARY KEY (`idestoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`categoria` (
  `idcatergoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idcatergoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `link_download` VARCHAR(100) NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `idestoque` INT NOT NULL,
  `categoria_idcatergoria` INT NOT NULL,
  PRIMARY KEY (`idproduto`, `idestoque`, `categoria_idcatergoria`),
  INDEX `fk_produto_estoque1_idx` (`idestoque` ASC) ,
  INDEX `fk_produto_categoria1_idx` (`categoria_idcatergoria` ASC) ,
  UNIQUE INDEX `link_download_UNIQUE` (`link_download` ASC) ,
  CONSTRAINT `fk_produto_estoque1`
    FOREIGN KEY (`idestoque`)
    REFERENCES `sys_ecommerce_db`.`estoque` (`idestoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_idcatergoria`)
    REFERENCES `sys_ecommerce_db`.`categoria` (`idcatergoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`idpagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `data_criacao` DATE NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `idpagamento` INT NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_compra_pagamento1_idx` (`idpagamento` ASC) ,
  CONSTRAINT `fk_compra_pagamento1`
    FOREIGN KEY (`idpagamento`)
    REFERENCES `sys_ecommerce_db`.`pagamento` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `menu` VARCHAR(45) NOT NULL,
  `link` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`imagem` (
  `idimagem` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `caminho` VARCHAR(100) NOT NULL,
  `data_criacao` DATE NOT NULL,
  `data_modificaco` DATE NOT NULL,
  `idproduto` INT NOT NULL,
  PRIMARY KEY (`idimagem`),
  INDEX `fk_imagem_produto1_idx` (`idproduto` ASC) ,
  CONSTRAINT `fk_imagem_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `sys_ecommerce_db`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`desconto` (
  `id_desconto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `porcentagem` DECIMAL NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_desconto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`desconto_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`desconto_produto` (
  `desconto_id_desconto` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`desconto_id_desconto`, `produto_idproduto`),
  INDEX `fk_desconto_has_produto_produto1_idx` (`produto_idproduto` ASC) ,
  INDEX `fk_desconto_has_produto_desconto1_idx` (`desconto_id_desconto` ASC) ,
  CONSTRAINT `fk_desconto_has_produto_desconto1`
    FOREIGN KEY (`desconto_id_desconto`)
    REFERENCES `sys_ecommerce_db`.`desconto` (`id_desconto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_desconto_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `sys_ecommerce_db`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(15) NULL,
  `email` VARCHAR(50) NULL,
  `status` TINYINT NOT NULL,
  `data_criacao` DATE NOT NULL,
  `data_modificado` DATE NOT NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `perfil_idperfil`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC) ,
  INDEX `fk_usuario_perfil1_idx` (`perfil_idperfil` ASC) ,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `sys_ecommerce_db`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`item_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`item_carrinho` (
  `idproduto` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `idcompra` INT NOT NULL,
  INDEX `fk_item_carrinho_produto1_idx` (`idproduto` ASC) ,
  INDEX `fk_item_carrinho_usuario1_idx` (`idusuario` ASC) ,
  INDEX `fk_item_carrinho_compra1_idx` (`idcompra` ASC) ,
  CONSTRAINT `fk_item_carrinho_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `sys_ecommerce_db`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_carrinho_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `sys_ecommerce_db`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_carrinho_compra1`
    FOREIGN KEY (`idcompra`)
    REFERENCES `sys_ecommerce_db`.`compra` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sys_ecommerce_db`.`menu_has_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys_ecommerce_db`.`menu_has_perfil` (
  `menu_idmenu` INT NOT NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`menu_idmenu`, `perfil_idperfil`),
  INDEX `fk_menu_has_perfil_perfil1_idx` (`perfil_idperfil` ASC) ,
  INDEX `fk_menu_has_perfil_menu1_idx` (`menu_idmenu` ASC) ,
  CONSTRAINT `fk_menu_has_perfil_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `sys_ecommerce_db`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_has_perfil_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `sys_ecommerce_db`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
